# Generated by Django 4.2.4 on 2023-08-27 11:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_a_visit',
            name='preferred_date_time',
        ),
        migrations.AddField(
            model_name='plan_a_visit',
            name='preferred_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 28, 11, 27, 4, 714845), validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 8, 27, 11, 27, 4, 714860))]),
        ),
        migrations.AddField(
            model_name='plan_a_visit',
            name='preferred_time',
            field=models.TimeField(default=datetime.time(11, 27, 4, 714887), validators=[django.core.validators.MinValueValidator(datetime.time(11, 27, 4, 714889))]),
        ),
    ]
