# Generated by Django 4.2.4 on 2023-08-27 12:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_plan_a_visit_preferred_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_a_visit',
            name='preferred_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 28, 12, 1, 45, 740928), validators=[django.core.validators.MinValueValidator(datetime.datetime)]),
        ),
        migrations.AlterField(
            model_name='plan_a_visit',
            name='preferred_time',
            field=models.TimeField(default=datetime.time(12, 1, 45, 740951), validators=[django.core.validators.MinValueValidator(datetime.time(12, 1, 45, 740953))]),
        ),
    ]
