# Generated by Django 4.2.4 on 2023-08-27 12:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_plan_a_visit_preferred_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_a_visit',
            name='preferred_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 28, 12, 2, 49, 831952), validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 8, 27, 12, 2, 49, 831964))]),
        ),
        migrations.AlterField(
            model_name='plan_a_visit',
            name='preferred_time',
            field=models.TimeField(default=datetime.time(12, 2, 49, 831985), validators=[django.core.validators.MinValueValidator(datetime.time(12, 2, 49, 831987))]),
        ),
    ]
