# Generated by Django 4.2.4 on 2023-08-27 12:05

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_plan_a_visit_preferred_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_a_visit',
            name='preferred_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 28, 12, 5, 26, 63480), validators=[django.core.validators.MinValueValidator(datetime.date(2023, 8, 27))]),
        ),
        migrations.AlterField(
            model_name='plan_a_visit',
            name='preferred_time',
            field=models.TimeField(default=datetime.time(12, 5, 26, 63521), validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 8, 27, 12, 5, 26, 63524, tzinfo=datetime.timezone.utc))]),
        ),
    ]
